export interface Newsletter {
  slug: string
  title: string
  issueLabel: string
  date: string
  year: number
  pdfPath: string
  coverImage: string
  coverColor: string
  sourceFile: string
}

const GRADIENTS = [
  'from-navy-700 to-teal-600',
  'from-warm-600 to-navy-700',
  'from-navy-700 to-warm-500',
  'from-teal-600 to-navy-600',
  'from-navy-600 to-sage-500',
  'from-warm-500 to-teal-600',
]

const NEWSLETTERS: Newsletter[] = [
  {
    slug: '2026-february',
    title: "Tomorrow's Child - February 2026",
    issueLabel: 'February 2026',
    date: '2026-02-01',
    year: 2026,
    pdfPath: '/newsletters/2026-february.pdf',
    coverImage: '/newsletters/covers/2026-february.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: '2026-TC-February-V5-Pages (1).pdf',
  },
  {
    slug: '2025-november',
    title: "Tomorrow's Child - November 2025",
    issueLabel: 'November 2025',
    date: '2025-11-01',
    year: 2025,
    pdfPath: '/newsletters/2025-november.pdf',
    coverImage: '/newsletters/covers/2025-november.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: '2025-TC-November-V4-Digital-Pages (1).pdf',
  },
  {
    slug: '2025-august',
    title: "Tomorrow's Child - August 2025",
    issueLabel: 'August 2025',
    date: '2025-08-01',
    year: 2025,
    pdfPath: '/newsletters/2025-august.pdf',
    coverImage: '/newsletters/covers/2025-august.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: '2025-TC-August-V3-Digital-Pages (1).pdf',
  },
  {
    slug: '2025-may',
    title: "Tomorrow's Child - May 2025",
    issueLabel: 'May 2025',
    date: '2025-05-01',
    year: 2025,
    pdfPath: '/newsletters/2025-may.pdf',
    coverImage: '/newsletters/covers/2025-may.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: '2025-May-TC-V4-Digital-Pages (1).pdf',
  },
  {
    slug: '2025-march',
    title: "Tomorrow's Child - March 2025",
    issueLabel: 'March 2025',
    date: '2025-03-01',
    year: 2025,
    pdfPath: '/newsletters/2025-march.pdf',
    coverImage: '/newsletters/covers/2025-march.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: '2025-March-TC-V3-Pages (1).pdf',
  },
  {
    slug: '2024-november',
    title: "Tomorrow's Child - November 2024",
    issueLabel: 'November 2024',
    date: '2024-11-01',
    year: 2024,
    pdfPath: '/newsletters/2024-november.pdf',
    coverImage: '/newsletters/covers/2024-november.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: '2024-November-TC-V6-Digital (1).pdf',
  },
  {
    slug: '2024-august',
    title: "Tomorrow's Child - August 2024",
    issueLabel: 'August 2024',
    date: '2024-08-01',
    year: 2024,
    pdfPath: '/newsletters/2024-august.pdf',
    coverImage: '/newsletters/covers/2024-august.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: '2024-August-TC-BackToSchool-V5-Digital-Pages (1).pdf',
  },
  {
    slug: '2024-may',
    title: "Tomorrow's Child - May 2024",
    issueLabel: 'May 2024',
    date: '2024-05-01',
    year: 2024,
    pdfPath: '/newsletters/2024-may.pdf',
    coverImage: '/newsletters/covers/2024-may.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: '2024-May-TC-V4-Pages-Digital.pdf',
  },
  {
    slug: '2024-february',
    title: "Tomorrow's Child - February 2024",
    issueLabel: 'February 2024',
    date: '2024-02-01',
    year: 2024,
    pdfPath: '/newsletters/2024-february.pdf',
    coverImage: '/newsletters/covers/2024-february.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: '2024-February-TC-Digital-Pages.pdf',
  },
  {
    slug: '2023-november',
    title: "Tomorrow's Child - November 2023",
    issueLabel: 'November 2023',
    date: '2023-11-01',
    year: 2023,
    pdfPath: '/newsletters/2023-november.pdf',
    coverImage: '/newsletters/covers/2023-november.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: '2023-November-TC-V6-Dig (3).pdf',
  },
  {
    slug: '2023-september',
    title: "Tomorrow's Child - September 2023",
    issueLabel: 'September 2023',
    date: '2023-09-01',
    year: 2023,
    pdfPath: '/newsletters/2023-september.pdf',
    coverImage: '/newsletters/covers/2023-september.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: '2023-September-TC-Final-Pages (1).pdf',
  },
  {
    slug: '2023-april',
    title: "Tomorrow's Child - April 2023",
    issueLabel: 'April 2023',
    date: '2023-04-01',
    year: 2023,
    pdfPath: '/newsletters/2023-april.pdf',
    coverImage: '/newsletters/covers/2023-april.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: '2023-April-TC-Digital-Pages (1).pdf',
  },
  {
    slug: '2023-february',
    title: "Tomorrow's Child - February 2023",
    issueLabel: 'February 2023',
    date: '2023-02-01',
    year: 2023,
    pdfPath: '/newsletters/2023-february.pdf',
    coverImage: '/newsletters/covers/2023-february.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: "Tomorrow_s Child February 2023.pdf",
  },
  {
    slug: '2022-november',
    title: "Tomorrow's Child - November 2022",
    issueLabel: 'November 2022',
    date: '2022-11-01',
    year: 2022,
    pdfPath: '/newsletters/2022-november.pdf',
    coverImage: '/newsletters/covers/2022-november.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: '2022-November-TC-Digital-Pages (1).pdf',
  },
  {
    slug: '2022-august',
    title: "Tomorrow's Child - August 2022",
    issueLabel: 'August 2022',
    date: '2022-08-01',
    year: 2022,
    pdfPath: '/newsletters/2022-august.pdf',
    coverImage: '/newsletters/covers/2022-august.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: '2022-August-TC-V4-Pages (1).pdf',
  },
  {
    slug: '2022-may',
    title: "Tomorrow's Child - May 2022",
    issueLabel: 'May 2022',
    date: '2022-05-01',
    year: 2022,
    pdfPath: '/newsletters/2022-may.pdf',
    coverImage: '/newsletters/covers/2022-may.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: "Tomorrow_s Child May 2022 (1).pdf",
  },
  {
    slug: '2022-january',
    title: "Tomorrow's Child - January 2022",
    issueLabel: 'January 2022',
    date: '2022-01-01',
    year: 2022,
    pdfPath: '/newsletters/2022-january.pdf',
    coverImage: '/newsletters/covers/2022-january.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: '2022-TC-January-V5-Pages.pdf',
  },
  {
    slug: '2021-september',
    title: "Tomorrow's Child - September 2021",
    issueLabel: 'September 2021',
    date: '2021-09-01',
    year: 2021,
    pdfPath: '/newsletters/2021-september.pdf',
    coverImage: '/newsletters/covers/2021-september.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: 'Tomorrow_s Child September 2021 (1).pdf',
  },
  {
    slug: '2021-may',
    title: "Tomorrow's Child - May 2021",
    issueLabel: 'May 2021',
    date: '2021-05-01',
    year: 2021,
    pdfPath: '/newsletters/2021-may.pdf',
    coverImage: '/newsletters/covers/2021-may.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: 'TC-MAY-2021-EB-V4 (1).pdf',
  },
  {
    slug: '2019-november',
    title: "Tomorrow's Child - November 2019",
    issueLabel: 'November 2019',
    date: '2019-11-01',
    year: 2019,
    pdfPath: '/newsletters/2019-november.pdf',
    coverImage: '/newsletters/covers/2019-november.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: 'TC-NOV-2019-FINAL_BLEEDS (1).pdf',
  },
  {
    slug: '2018-october',
    title: "Tomorrow's Child - October 2018",
    issueLabel: 'October 2018',
    date: '2018-10-01',
    year: 2018,
    pdfPath: '/newsletters/2018-october.pdf',
    coverImage: '/newsletters/covers/2018-october.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: 'october18-TC-FINAL.pdf',
  },
  {
    slug: '2018-may',
    title: 'NewGate Newsletter - May 2018',
    issueLabel: 'May 2018',
    date: '2018-05-01',
    year: 2018,
    pdfPath: '/newsletters/2018-may.pdf',
    coverImage: '/newsletters/covers/2018-may.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: 'NewGate Newsletter May 2018 (1).pdf',
  },
  {
    slug: '2017-august',
    title: "Tomorrow's Child - August 2017",
    issueLabel: 'August 2017',
    date: '2017-08-01',
    year: 2017,
    pdfPath: '/newsletters/2017-august.pdf',
    coverImage: '/newsletters/covers/2017-august.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: 'TC-AUGUST-2017.pdf',
  },
  {
    slug: '2016-september',
    title: "Tomorrow's Child - September 2016",
    issueLabel: 'September 2016',
    date: '2016-09-01',
    year: 2016,
    pdfPath: '/newsletters/2016-september.pdf',
    coverImage: '/newsletters/covers/2016-september.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: "Tomorrow_s Child September 2016 (1).pdf",
  },
  {
    slug: '2016-april',
    title: "Tomorrow's Child - April 2016",
    issueLabel: 'April 2016',
    date: '2016-04-01',
    year: 2016,
    pdfPath: '/newsletters/2016-april.pdf',
    coverImage: '/newsletters/covers/2016-april.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: "Tomorrow_s Child April 2016 (1).pdf",
  },
  {
    slug: '2016-january',
    title: "Tomorrow's Child - January 2016",
    issueLabel: 'January 2016',
    date: '2016-01-01',
    year: 2016,
    pdfPath: '/newsletters/2016-january.pdf',
    coverImage: '/newsletters/covers/2016-january.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: "Tomorrow_s Child January 2016.pdf",
  },
  {
    slug: '2015-november',
    title: "Tomorrow's Child - November 2015",
    issueLabel: 'November 2015',
    date: '2015-11-01',
    year: 2015,
    pdfPath: '/newsletters/2015-november.pdf',
    coverImage: '/newsletters/covers/2015-november.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: "Tomorrow_s Child November, 2015.pdf",
  },
  {
    slug: '2015-september',
    title: "Tomorrow's Child - September 2015",
    issueLabel: 'September 2015',
    date: '2015-09-01',
    year: 2015,
    pdfPath: '/newsletters/2015-september.pdf',
    coverImage: '/newsletters/covers/2015-september.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: "Tomorrow_s Child September 2015 (1).pdf",
  },
  {
    slug: '2015-april',
    title: "Tomorrow's Child - April 2015",
    issueLabel: 'April 2015',
    date: '2015-04-01',
    year: 2015,
    pdfPath: '/newsletters/2015-april.pdf',
    coverImage: '/newsletters/covers/2015-april.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: 'Tomorrow Child April 2015.pdf',
  },
  {
    slug: '2015-january',
    title: "Tomorrow's Child - January 2015",
    issueLabel: 'January 2015',
    date: '2015-01-01',
    year: 2015,
    pdfPath: '/newsletters/2015-january.pdf',
    coverImage: '/newsletters/covers/2015-january.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: 'Tomorrows Child January 2015.pdf',
  },
  {
    slug: '2014-november',
    title: "Tomorrow's Child - November 2014",
    issueLabel: 'November 2014',
    date: '2014-11-01',
    year: 2014,
    pdfPath: '/newsletters/2014-november.pdf',
    coverImage: '/newsletters/covers/2014-november.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: 'TC NOV 2014.pdf',
  },
  {
    slug: '2014-august',
    title: "Tomorrow's Child - August 2014",
    issueLabel: 'August 2014',
    date: '2014-08-01',
    year: 2014,
    pdfPath: '/newsletters/2014-august.pdf',
    coverImage: '/newsletters/covers/2014-august.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: "Tomorrow_s Child TC August 2014 (1).pdf",
  },
  {
    slug: '2014-november-magazine',
    title: "Tomorrow's Child Magazine - November 2014",
    issueLabel: 'November 2014 (Magazine)',
    date: '2014-11-15',
    year: 2014,
    pdfPath: '/newsletters/2014-november-magazine.pdf',
    coverImage: '/newsletters/covers/2014-november-magazine.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: "Tomorrow_s Child Magazine November-TC (1).pdf",
  },
  {
    slug: '2012-april',
    title: "Tomorrow's Child - April 2012",
    issueLabel: 'April 2012',
    date: '2012-04-01',
    year: 2012,
    pdfPath: '/newsletters/2012-april.pdf',
    coverImage: '/newsletters/covers/2012-april.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: 'Tomorrows+Child+April+2012.pdf',
  },
  {
    slug: '2010-september',
    title: "Tomorrow's Child - September 2010",
    issueLabel: 'September 2010',
    date: '2010-09-01',
    year: 2010,
    pdfPath: '/newsletters/2010-september.pdf',
    coverImage: '/newsletters/covers/2010-september.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: 'TC_Sept-2010.pdf',
  },
  // Special publications
  {
    slug: '2016-how-to-spot-montessori',
    title: 'How To Spot A Montessori Classroom',
    issueLabel: 'How To Spot a Montessori Classroom',
    date: '2016-04-15',
    year: 2016,
    pdfPath: '/newsletters/2016-how-to-spot-montessori.pdf',
    coverImage: '/newsletters/covers/2016-how-to-spot-montessori.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: 'How To Spot A Montessori Classroom TC-april 2016 (1).pdf',
  },
  {
    slug: 'montessori-101',
    title: 'Montessori 101 - 2021 Edition',
    issueLabel: 'Montessori 101',
    date: '2021-01-01',
    year: 2021,
    pdfPath: '/newsletters/montessori-101.pdf',
    coverImage: '/newsletters/covers/montessori-101.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: 'Montessori 101 - 2021 Edition.pdf',
  },
  {
    slug: 'first-days-of-school',
    title: 'First Days of School',
    issueLabel: 'First Days of School',
    date: '2020-08-01',
    year: 2020,
    pdfPath: '/newsletters/first-days-of-school.pdf',
    coverImage: '/newsletters/covers/first-days-of-school.jpg',
    coverColor: GRADIENTS[1],
    sourceFile: 'First Days of School.pdf',
  },
  {
    slug: 'montessori-way',
    title: 'The Montessori Way',
    issueLabel: 'The Montessori Way',
    date: '2020-01-01',
    year: 2020,
    pdfPath: '/newsletters/montessori-way.pdf',
    coverImage: '/newsletters/covers/montessori-way.jpg',
    coverColor: GRADIENTS[2],
    sourceFile: 'The Montessori Way - by Tim Seldin and Dr. Paul Epstein (1).pdf',
  },
  {
    slug: 'montessori-leadership-2022-january',
    title: 'Montessori Leadership - January 2022',
    issueLabel: 'Leadership Jan 2022',
    date: '2022-01-15',
    year: 2022,
    pdfPath: '/newsletters/montessori-leadership-2022-january.pdf',
    coverImage: '/newsletters/covers/montessori-leadership-2022-january.jpg',
    coverColor: GRADIENTS[3],
    sourceFile: 'Montessori Leadership_JAN_ISSUE 1_2022 (1).pdf',
  },
  {
    slug: 'montessori-leadership-2021-november',
    title: 'Montessori Leadership - November 2021',
    issueLabel: 'Leadership Nov 2021',
    date: '2021-11-01',
    year: 2021,
    pdfPath: '/newsletters/montessori-leadership-2021-november.pdf',
    coverImage: '/newsletters/covers/montessori-leadership-2021-november.jpg',
    coverColor: GRADIENTS[4],
    sourceFile: 'Montessori Leadership November 2021.pdf',
  },
  {
    slug: 'montessori-creativity-leadership',
    title: 'Montessori Creativity in Leadership',
    issueLabel: 'Creativity in Leadership',
    date: '2020-06-01',
    year: 2020,
    pdfPath: '/newsletters/montessori-creativity-leadership.pdf',
    coverImage: '/newsletters/covers/montessori-creativity-leadership.jpg',
    coverColor: GRADIENTS[5],
    sourceFile: 'Montessori+creativity+in+leadership+Briefings+Magazine (2).pdf',
  },
  {
    slug: 'ml-magazine',
    title: 'Montessori Leadership Magazine',
    issueLabel: 'ML Magazine',
    date: '2020-03-01',
    year: 2020,
    pdfPath: '/newsletters/ml-magazine.pdf',
    coverImage: '/newsletters/covers/ml-magazine.jpg',
    coverColor: GRADIENTS[0],
    sourceFile: 'ML_Magazine_Artwork_r2_Output_wo-cropmark (1) (1).pdf',
  },
]

export function getAllNewsletters(): Newsletter[] {
  return [...NEWSLETTERS].sort((a, b) => b.date.localeCompare(a.date))
}

export function getLatestNewsletter(): Newsletter {
  return getAllNewsletters()[0]
}

export function getNewsletterBySlug(slug: string): Newsletter | undefined {
  return NEWSLETTERS.find(n => n.slug === slug)
}

export function getNewslettersByYear(year: number): Newsletter[] {
  return getAllNewsletters().filter(n => n.year === year)
}
