// Generates lib/articles-metadata.ts from lib/articles.ts.
//
// lib/articles.ts (auto-generated from the WordPress export) remains the
// single source of truth and keeps full bodies — it is imported ONLY by
// server-rendered code (the article reader and Abigail's system prompt).
// Discovery surfaces (Explore, Library list, Home, Abigail client helpers)
// import the metadata module instead, so ~500 article bodies never ship in
// client bundles.
//
// Re-run after regenerating articles.ts:
//   npx tsx scripts/generate-article-metadata.ts

import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { ARTICLES } from '../lib/articles'

const meta = ARTICLES.map(a => ({
  slug: a.slug,
  title: a.title,
  // Some WordPress-exported authors are raw email addresses — never show
  // an email as a byline in discovery cards.
  author: a.author.includes('@') ? 'The Montessori Foundation' : a.author,
  date: a.date,
  categories: a.categories,
  tags: a.tags,
  excerpt: a.excerpt,
  videoIds: a.videoIds?.length ? a.videoIds : undefined,
  readMinutes: Math.max(2, Math.round((a.content || '').split(/\s+/).length / 220)),
}))

const header = `// AUTO-GENERATED by scripts/generate-article-metadata.ts — do not edit.
// Source of truth: lib/articles.ts (regenerate this file after updating it).
// Discovery metadata only — article bodies stay server-side in lib/articles.ts.

export interface ArticleMeta {
  slug: string
  title: string
  author: string
  date: string
  categories: string[]
  tags: string[]
  excerpt: string
  videoIds?: string[]
  readMinutes: number
}

export const ARTICLE_META: ArticleMeta[] = `

const helpers = `

export function getAllArticleMeta(): ArticleMeta[] {
  return ARTICLE_META
}

export function getArticleMetaBySlug(slug: string): ArticleMeta | undefined {
  return ARTICLE_META.find(a => a.slug === slug)
}

export function getArticleMetaByCategory(category: string): ArticleMeta[] {
  return ARTICLE_META.filter(a => a.categories.includes(category))
}

export function getAllCategories(): string[] {
  const set = new Set<string>()
  ARTICLE_META.forEach(a => a.categories.forEach(c => set.add(c)))
  return Array.from(set).sort()
}

export function getAllTags(): string[] {
  const set = new Set<string>()
  ARTICLE_META.forEach(a => a.tags.forEach(t => set.add(t)))
  return Array.from(set).sort()
}
`

writeFileSync(
  join(process.cwd(), 'lib', 'articles-metadata.ts'),
  header + JSON.stringify(meta, null, 2).replace(/"([A-Za-z_][A-Za-z0-9_]*)":/g, '$1:') + helpers,
  'utf8',
)

console.log(`Wrote lib/articles-metadata.ts with ${meta.length} article records`)
